### default config ###

server.port: 9061

server.contextPath: /BussinessB

logging.config: classpath:config/logback.xml
global.feign.client.config.maxAttempts: 3


### development and test config ###
---

spring.profiles: development


spring.datasource.url: jdbc:mysql://127.0.0.1:3306/rdb_server_compute_db?characterEncoding=UTF-8&useSSL=false
spring.datasource.username: dba
spring.datasource.password: mysql

eureka.client.serviceUrl.defaultZone: http://127.0.0.1:9910/eureka



---

spring.profiles: test

spring.jpa.properties.hibernate.hbm2ddl.auto: validate
spring.jpa.open-in-view: true


login.path: /login
auth.jwt.url.auth: /auth
auth.jwt.header.name: Authorization
auth.jwt.header.prefix: Bearer
auth.jwt.cookie.name: JTOKEN
auth.jwt.expiration: 604800 # one week = 7 * 24 * 60 * 60
auth.jwt.cert.private: key/private_key.der
auth.jwt.algorithm.type: RSA
auth.jwt.cert.public: key/public_key.der

spring.cloud.bus.enabled: false
spring.jmx.enabled: false
eureka.client.registerWithEureka: false
eureka.client.fetchRegistry: false
global.service.version: version
global.chart.version:

### production config ###
---

spring.profiles: production

logging.file: /Users/user/xxl/log/service/xxl-spring/BussinessB.log
