# springboot 2.0 之前用server.context-path
#server.contextPath: /SerializedService
# springboot 2.0 之后 改为server.servlet.context-path
server:
  port: 9092
  servlet:
    context-path: /


## 数据源配置
#spring.datasource.url: jdbc:mysql://localhost:3306/xxl_jdbc?useUnicode=true&characterEncoding=utf8
#spring.datasource.username: root
#spring.datasource.password: helloroot
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#
### Mybatis 配置
#mybatis.typeAliasesPackage: com.xxl.model
#mybatis.mapperLocations: classpath:mapper/*.xml


## master 数据源配置 CREATE SCHEMA `xxl_jdbc2` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
master.datasource.url: jdbc:mysql://localhost:3306/xxl_jdbc2?useUnicode=true&characterEncoding=utf8
master.datasource.username: root
master.datasource.password: helloroot
master.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

## cluster 数据源配置
cluster.datasource.url: jdbc:mysql://localhost:3306/xxl_jdbc?useUnicode=true&characterEncoding=utf8
cluster.datasource.username: root
cluster.datasource.password: helloroot
cluster.datasource.driver-class-name: com.mysql.cj.jdbc.Driver


## Redis 配置
## Redis数据库索引（默认为0）
spring.redis.database: 0
## Redis服务器地址
spring.redis.host: 127.0.0.1
## Redis服务器连接端口
spring.redis.port: 6379
## Redis服务器连接密码（默认为空）
spring.redis.password:
## 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
## 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
## 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
## 连接超时时间（毫秒）
spring.redis.timeout: 0