server.port: 9111

server.contextPath: /
logging.config: classpath:config/logback.xml
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:9910/eureka
global.feign.client.config.maxAttempts: 3

spring.profiles.active: development



### development and test config ###
---

spring.profiles: development

datasource.master.port: 3306

global.monitoring.enabled: true

---

spring.profiles: test

spring.jpa.properties.hibernate.hbm2ddl.auto: validate
spring.jpa.open-in-view: true

### production config ###
---

spring.profiles: production

logging.file: /Users/user/xxl/log/service/xxl-spring/study.log