version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - cluster.name=xxl-es
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
  kibana:
    image: elastic/kibana:7.12.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://127.0.0.1:9200
    ports:
      - "5601:5601"